# `dbt_project/profiles.yml`
snowflake_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 4
      # Placeholder values are required for dbt validation but are
      # ignored by Snowflake, which uses session context instead.
      # account: placeholder
      # user: placeholder
      # password: placeholder
      # role: placeholder
      # warehouse: placeholder
      database: FEATURE_TEST_DB
      # schema: placeholder
